### ISSUE TITLE
Bilibili Support

### ISSUE THREAD

**Issue by NADESHIKON** [soruly/trace.moe#27]
as included in the title, Bilibili is a Chinese website which does the same things as MyAnimeList & AniList

https://bilibili.com

I would appreciate that if you implement the support for Bilibili :)

Sincerely,
Allen

**Comment by soruly** [comment]
As explained in #21 , I have plans to index video websites like youtube, niconico, bilibili
But I'm quite busy now, and priority is now given to complete https://github.com/soruly/sola first

**Comment by soruly** [comment]
話說現在也有不少搬運工把影片搬到BT網絡，所以資料庫索引裡也有不少bilibili的影片，只是無法追蹤原始地址

**Comment by allenlol** [comment]
yep
