### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by nkonin** [soruly/trace.moe#33]
It would be nice to have Dockerfile in project

**Comment by soruly** [comment]
This project only include the front-end webpage, the backend system is powered by sola
https://github.com/soruly/sola
That project is already dockerized and you should try that out.
For this frond-end repo, I've no high priority to dockerize it yet.

**Comment by soruly** [comment]
All parts are dockerized now. You can follow this guide to setup your own system.

https://github.com/soruly/trace.moe#hosting-your-own-tracemoe-system
