### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by XakepSDK** [soruly/trace.moe#34]
Service finds only and only `Tantei Gakuen Q`.
For example:
I'm searching this:
https://tmp.saucenao.com/userdata/52832dc5a1d142d220ff24ed2dccb577e87948e4_1548080384.png
And service says, that this is `Tantei Gakuen Q`
Result:
https://puu.sh/CA5Ea/801ca25c73.png

**Comment by soruly** [comment]
I cannot see the image on saucenao, can you upload directly here to github?

**Comment by XakepSDK** [comment]
![image](https://user-images.githubusercontent.com/4938483/51481303-79a49680-1d8b-11e9-99c8-6982c3a8def1.png)

**Comment by soruly** [comment]
I think the server cannot find anything relavent, that was just a visually similar scene.

**Comment by soruly** [comment]
I think it's the preview broken, not the search broken
What browser are you using?

**Comment by XakepSDK** [comment]
Firefox 65.0b11 with canvas disabled

**Comment by soruly** [comment]
Oh, the website requires canvas to work, so it wont work unless you enable that
If you insist to disable canvas, you may use the telegram bot https://t.me/whatanimebot

**Comment by XakepSDK** [comment]
Ah... Thank you. I can't enable canvas and can't use telegram bot(dollchan script with frame search function)
I hope, someday this will be fixed.
