### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by Blueberryy** [soruly/trace.moe#38]
:p

**Comment by soruly** [comment]
Do you think I should also translate text on changelog and faq? that's quite a lot of work

**Comment by Kadantte** [comment]
@soruly As ppl if they coulda help with translating it's Ok otherwise no need for it :3 .

**Comment by cr998** [comment]
i can help you in the translation proccess

**Comment by soruly** [comment]
You can take a look at some previous attempts of translations.

Translation is not a one-off process, you also have to keep translation up-to-date all the time. Given that new contents would be added from time to time. It's a long term commitment.

https://github.com/soruly/trace.moe/pull/31
