### ISSUE TITLE
HTTP 500 when using search api

### ISSUE THREAD

**Issue by Komica20160704** [soruly/trace.moe#42]
Hi, I use the [api](https://soruly.github.io/trace.moe) to get some useful information for my images.
A few chance, I got the error.

```
POST https://trace.moe/api/search
ResponseError (Code 500 - "Error reading image from URL: http://192.168.2.11/pic/1556121770.7361.jpg: null"):
```

Want to know how did it happen or how can I detect my images to find out problem images.

---

The image I post
![1385230255035](https://user-images.githubusercontent.com/20284960/56676029-009d3e00-66f0-11e9-8902-1e8c9228fd9c.jpg)

**Comment by Geo1088** [comment]
What API call are you making that returns this error?

**Comment by Komica20160704** [comment]
> What API call are you making that returns this error?

Sorry, I lost it. It happen when I use the search api.
`POST https://trace.moe/api/search`

**Comment by soruly** [comment]
This is not an API specific error, using the same image with webpage I've also got the same error.
From server side, the temp image for this is empty (0 file size).
It seems something is wrong when cropping black border, resulting an image with 0 width height

**Comment by Komica20160704** [comment]
Thank you!
