### ISSUE TITLE
image-proxy and Discord

### ISSUE THREAD

**Issue by SentientCrab** [soruly/trace.moe#48]
image-proxy fails on discord, says "This content is no longer available"

Edit: example url for testing https://cdn.discordapp.com/attachments/473214112969654282/676078778396573706/unknown.png

**Comment by soruly** [comment]
Yes this is an known issue. I'm not sure what was causing it. Probably because both Discord and trace.moe are served via cloudflare, which may be blocked by some firewall settings on Discord's server side?

**Comment by SentientCrab** [comment]
What about a setting to disable image proxy and do the request client side?

**Comment by soruly** [comment]
> What about a setting to disable image proxy and do the request client side?

This would be blocked by browsers' security policy

**Comment by SentientCrab** [comment]
Oh duh, always forget about CORS being bad

**Comment by ImUrX** [comment]
CORS has its own reasons for existing... and its configurable by the site :p

**Comment by soruly** [comment]
> CORS has its own reasons for existing... and its configurable by the site :p

Yes it's possible to load the image with CORS, but then the image would become "tainted canvas", which cannot be convereted to binary format to via toBlob or toDataURI.

**Comment by ImUrX** [comment]
sorry, not saying it should be done. i havent checked the codebase :p

**Comment by soruly** [comment]
Resolved in da5a1135311fba81a0bc6883425e2b5b6c684c67

ref: https://github.com/soruly/trace.moe-image-proxy

**Comment by soruly** [comment]
now.sh (ZEIT, a.k.a Vercel) blocked the image proxy because it's not allowed in its fair use policy. Now switching back to cloudflare workers for the moment. Need to look for new solutions.
