### ISSUE TITLE
Connection to Search Server Failed

### ISSUE THREAD

**Issue by i-loli** [soruly/trace.moe#55]
An error occurred while running the program.

**Comment by 2209901700** [comment]
I download the program directly from gitub and run it directly on the server without any modification. The test environment is located in China.Due to limited technology, how to deal with it? Thank you!

**Comment by soruly** [comment]
The repository only contains the front end of trace.moe, the backend it https://github.com/soruly/sola which requires you to index your own anime and host it in your own database instance

**Comment by i-loli** [comment]
thinks
