### ISSUE TITLE
it works okay for some animes but is kinda broken so when will it be out of beta?

### ISSUE THREAD

**Issue by sanidhya711** [soruly/trace.moe#63]
btw do u own twist.moe?

**Comment by soruly** [comment]
Unless I've found a effective way to separate similar results and matching results, maybe. And it's actually a anime scene search engine, rather than a AI recognition neural network. Maybe it'd be always beta. P.S. I don't own twist.moe.

**Comment by MiTereKun** [comment]
@sanidhya711 According to my observations, during all 3 years, the percentage of incorrect definitions of anime names has not decreased. But it's still a big plus that there is such a service in general and that it is free. It’s a kashmare to store the series themselves for determination on the servers and constantly refer to them - this is an ice hole in costs, and cloud services usually put terribly high price tags, even wasabi oboko. By my standards, only real philontropists can afford
