### ISSUE TITLE
How do I get the video?

### ISSUE THREAD

**Issue by taksumaki** [soruly/trace.moe#64]
I try to generate the url but the "start" and "end" properties are missing, the api does not give them therefore I cannot generate the video

![image](https://user-images.githubusercontent.com/56084970/102300109-e560f100-3f19-11eb-9641-9a249c7ee4dd.png)

**Comment by soruly** [comment]
The website doesn't use the same API, please don't use the website's HTTP request as reference. You cannot specify the start / end param for that. All you need is `?t=`

**Comment by taksumaki** [comment]
@soruly Why can't I get the video?
This is the url that I try to put:
```
https://trace.moe/1374/強殖装甲ガイバー  第23話 「殲滅の光芒 ( Ray of Annihilation )」[BDrip X264 AAC 720P].mp4?t=996.83&token=_PUz-qQ8WYwsxs9wtvcCMw
```

These are the data that I obtain and use:
```json
    {
      "from": 996.83,
      "to": 996.92,
      "anilist_id": 1374,
      "at": 996.92,
      "season": "2005-07",
      "anime": "強殖裝甲",
      "filename": "強殖装甲ガイバー  第23話 「殲滅の光芒 ( Ray of Annihilation )」[BDrip X264 AAC 720P].mp4",
      "episode": 23,
      "tokenthumb": "_PUz-qQ8WYwsxs9wtvcCMw",
      "similarity": 0.8077645720471075,
      "title": "強殖装甲ガイバー",
      "title_native": "強殖装甲ガイバー",
      "title_chinese": "強殖裝甲",
      "title_english": "Guyver: Bioboosted Armor",
      "title_romaji": "Kyoushoku Soukou Guyver (2005)",
      "mal_id": 1374,
      "synonyms": 
      [
        "Guyver: The Bio-boosted Armor"
      ],
      "synonyms_chinese": 
      [
        "強殖裝甲凱普"
      ],
      "is_adult": false
    },
```

But I get error 403, I don't know how I would have to compose the url to get the video or if this is how I should do it

**Comment by soruly** [comment]
You're using the wrong API endpoint, please read

https://soruly.github.io/trace.moe/

**Comment by taksumaki** [comment]
Oh perfect i get it, is there a way to prevent nsfw content from appearing?

**Comment by soruly** [comment]
You need to filter the search result by `is_adult` yourself

**Comment by taksumaki** [comment]
Thanks for the help, everything has been clear to me.
