### ISSUE TITLE
Old API ignores parameters in image url

### ISSUE THREAD

**Issue by FeeeeK** [soruly/trace.moe#67]
URL and image:
`https%3A%2F%2Fsun9-48.userapi.com%2Fimpc%2Fc536236%2Fu260636618%2Fd36%2F-3%2Fx_59e97016fe.jpg%3Fsize%3D192x108%26quality%3D90%26sign%3D651591e6e50f749a592d208dd172f9f6%26c_uniq_tag%3DaywHZuVfPT7F_ti_slrZyBT_RruSO68K2_52ZMtvZRs`
![image](https://user-images.githubusercontent.com/26704473/107889518-35613180-6f24-11eb-99c3-3b451ce6a4a8.png)

api.trace.moe works fine (but finds the wrong anime):
![image](https://user-images.githubusercontent.com/26704473/107889516-2b3f3300-6f24-11eb-93fb-6d7496e4f33e.png)

But trace.moe/api/search throws error:
![image](https://user-images.githubusercontent.com/26704473/107889543-6477a300-6f24-11eb-846f-c669ed363233.png)

**Comment by soruly** [comment]
Should be fixed now, please try again
