### ISSUE TITLE
Add support for pasting images from clipboard

### ISSUE THREAD

**Issue by Orzelius** [soruly/trace.moe#72]
Title.

Currently on firefox 91.0, pasting images (not urls, but images) into the search-box doesn't work. I think this would be a nice small feature.

**Comment by soruly** [comment]
It works for me on Firefox 91.0.1 (Windows 10)
When the Image URL input is focused, it would only accept text. You have to past the image outside of the box.

**Comment by soruly** [comment]
Alright, I've figured out that we can actually allow pasting image or text to the same input box.
Fixed at commit https://github.com/soruly/trace.moe-www/commit/d01aea0d5fe35f3916cced0877ffdcae94723bba
