### ISSUE TITLE
Could you create a version for windows 10?

### ISSUE THREAD

**Issue by My12123** [soruly/trace.moe#84]
Could you create a version for windows 10?

**Comment by My12123** [comment]
invalid mount config for type "bind": field Source must not be empty
![2022-12-27_21-17-22](https://user-images.githubusercontent.com/49092250/209706524-27bf516b-3446-4bf4-9206-51ea6fca7010.png)

**Comment by soruly** [comment]
It seems that you have not created the .env file. Have you been following the guide in README?

**Comment by My12123** [comment]
Yes, I was following.
![2022-12-28_10-11-04](https://user-images.githubusercontent.com/49092250/209773081-8019ab11-6ba6-4eb2-a73c-2d89acb634c8.png)

**Comment by My12123** [comment]
I failed to execute the command sudo chown 8983:8983 /home/soruly/mycores

**Comment by My12123** [comment]
![2022-12-28_11-11-53](https://user-images.githubusercontent.com/49092250/209780378-efb0e141-7110-4106-b664-5faa3769e985.png)

**Comment by My12123** [comment]
Can you make a video installation instruction for Windows 10?

**Comment by soruly** [comment]
I'll create a guide for linux when I've time. But windows 10 isn't something I'd like to support. I'm not interested in running docker with WSL2

**Comment by soruly** [comment]
> I'll create a guide for linux when I've time. But windows 10 isn't something I'd like to support. I'm not interested in running docker with WSL2

WSL2 is now supported.
