### ISSUE TITLE
Can you create a version for Google Colab?

### ISSUE THREAD

**Issue by My12123** [soruly/trace.moe#85]
Can you create a version for Google Colab?

**Comment by soruly** [comment]
trace.moe doesn't use python. I think it's not suitable to run on Colab.

**Comment by My12123** [comment]
You can also install Docker in Google Colab.
https://gist.github.com/mwufi/6718b30761cd109f9aff04c5144eb885
![2023-01-02_11-28-56](https://user-images.githubusercontent.com/49092250/210208335-d57687d0-6213-4e8f-a662-a778b0e0aad0.png)
![2023-01-02_11-30-30](https://user-images.githubusercontent.com/49092250/210208483-f344abeb-230a-461c-8491-f9eea1937873.png)

**Comment by My12123** [comment]
https://colab.research.google.com/drive/1noviu_b_w6GfNJfDBkXCGH1SMcl5dWxN?usp=sharing

**Comment by My12123** [comment]
Where else can we launch?

**Comment by soruly** [comment]
trace.moe is not a simple program, the whole system consists of many parts.
I think using docker-compose is already the easiest way to launch the whole thing.
Some other developers did launch the whole thing successfully on Ubuntu, you just need some more knowledge on linux, docker and networking.

**Comment by My12123** [comment]
Can you help me with this?
![2023-01-03_12-49-10](https://user-images.githubusercontent.com/49092250/210333950-f7d0dbbc-9391-4b22-8099-419b4c5a0381.png)
What should be corrected and how?

**Comment by soruly** [comment]
Please follow the instructions in README.md

**Comment by My12123** [comment]
Is there any need to change, if anything and for what? 
![image](https://user-images.githubusercontent.com/49092250/210405849-5b0a4fe9-fd3d-4f92-a231-ce4ae90bb8c3.png)

**Comment by Leslie-Wong-H** [comment]
Change these to your local win10 folders, and add "network: trace_moe_net" to every project of the docker-compose file. 
![image](https://user-images.githubusercontent.com/27696701/210768542-91931d27-102f-4c9f-ac7b-5c8ca27e1a43.png)

**Comment by soruly** [comment]
> Have you created these five folders locally?

Yes

**Comment by My12123** [comment]
Yeah, I made the dads.
![2023-01-05_22-17-28](https://user-images.githubusercontent.com/49092250/210862452-196be444-fa5e-4ba1-812c-f0ca6e7ac14a.png)
