### ISSUE TITLE
Can it be run on Hugging Face (huggingface.co)? If so, how?

### ISSUE THREAD

**Issue by My12123** [soruly/trace.moe#88]
Hugging Face supports the following environments:
![2023-01-21_18-24-16](https://user-images.githubusercontent.com/49092250/213873825-7623e0f5-18f7-4006-af00-372e8a3f5cf7.png)
Can it be run on Hugging Face (huggingface.co)? If so, how?

**Comment by My12123** [comment]
![2023-01-21_18-25-36](https://user-images.githubusercontent.com/49092250/213873874-933f478e-bf38-40f3-a4f2-ea2cdc44055e.png)

**Comment by soruly** [comment]
The current system requires 128GB RAM and ~200GB nvme SSD storage to run. I don't know if it's possbile to run on hugging face.

**Comment by Leslie-Wong-H** [comment]
> ![2023-01-21_18-25-36](https://user-images.githubusercontent.com/49092250/213873874-933f478e-bf38-40f3-a4f2-ea2cdc44055e.png)

I  checked Huggingface's documentation. They just support running a single docker container now. 

If you are familiar with docker-compose, you can use this optimized search engine to try, https://github.com/shotit/shotit/blob/main/docker-compose.yml.

It instead uses a vector database under the hood to provide blazing-fast search functionality. Deployed at a 4V32G Ubuntu machine, it can search 70 million vectors 3700+ episodes in seconds, with long-term RAM of about 20G. 

v0.9.3 is working, yet not much documentation is provided at the moment. Sorry. 

The procedure is similar to what soruly have described at README here. `docker-compose up -d` and place /anlist/epsode.mp4 files to volumes/shotit-incoming

```shell
git clone https://github.com/shotit/shotit.git
```
![image](https://user-images.githubusercontent.com/27696701/235381151-05ffc2c7-56d3-497a-8707-85aa2eea1181.png)

**Comment by soruly** [comment]
Let's get back to this when hugging face supports docker-compose
